# Generated by Django 3.2.7 on 2021-10-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_book', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('totaldemrev', models.DecimalField(decimal_places=2, max_digits=18)),
                ('donrgrntoptdev', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unspentgrnt', models.DecimalField(decimal_places=2, max_digits=18)),
                ('otherreceipts', models.DecimalField(decimal_places=2, max_digits=18)),
                ('trddbe', models.DecimalField(decimal_places=2, max_digits=18)),
                ('totrbexpenditure', models.DecimalField(decimal_places=2, max_digits=18)),
                ('batab', models.DecimalField(decimal_places=2, max_digits=18)),
                ('batar', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bauspenta', models.DecimalField(decimal_places=2, max_digits=18)),
                ('baexpenditure', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frrlotfa', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frrctamod', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frrctamoi', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frrtdf', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frrimfloan', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frrcashreverse', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frreroupcommission', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frreroupcomrefugee', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frrusdevaids', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frrartfip', models.DecimalField(decimal_places=2, max_digits=18)),
                ('freartfwb', models.DecimalField(decimal_places=2, max_digits=18)),
                ('freadb', models.DecimalField(decimal_places=2, max_digits=18)),
                ('freusaid', models.DecimalField(decimal_places=2, max_digits=18)),
                ('freotherdonrs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date', models.DateField(auto_now=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='budget_book.year')),
            ],
        ),
    ]
